/****** Script for SelectTopNRows command from SSMS  ******/
SELECT
	[Date]
      --,[Day Number]
      --,[Day]
      --,[Month]
      ,[Short Month]
      --,[Calendar Month Number]
      --,[Calendar Month Label]
      ,[Calendar Year]
      --,[Calendar Year Label]
      --,[Fiscal Month Number]
      --,[Fiscal Month Label]
      --,[Fiscal Year]
      --,[Fiscal Year Label]
      --,[ISO Week Number]
  FROM [WideWorldImportersDW].[Dimension].[Date]